# Generated by Django 4.2.7 on 2024-01-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
