# Generated by Django 4.2.7 on 2024-01-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_pollquestion_polloption'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=300)),
                ('options', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='PollOption',
        ),
        migrations.DeleteModel(
            name='PollQuestion',
        ),
    ]
