# Generated by Django 4.2.7 on 2024-01-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0017_rename_options_saverecord_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saverecord',
            old_name='option',
            new_name='choose',
        ),
    ]
